export const TagData = [
  { name: "Tools", slug: "tools", emoji: "🛠" },
  {
    name: "Automotive",
    slug: "automotive",
    description: "Car related stuff.",
    emoji: "🏎️",
  },
  {
    name: "Construction",
    slug: "construction",
    description:
      'Construction is a general term meaning the art and science to form objects, systems, or organizations,[1] and comes from Latin constructio (from com- "together" and struere "to pile up") and Old French construction. To construct is the verb: the act of building, and the noun is construction: how something is built, the nature of its structure.',
    emoji: "🚧",
  },
  { name: "Manufacturing", slug: "manufacturing", emoji: "🏭" },
  { name: "Agriculture", slug: "agriculture", emoji: "🧑‍🌾" },
  { name: "Energy", slug: "energy", emoji: "⚡" },
  { name: "Technology", slug: "technology", emoji: "🧑‍💻" },
  { name: "Tires", slug: "tires", emoji: "🛞" },
  { name: "Aerospace", slug: "aerospace", emoji: "🛫" },
  { name: "Clothing", slug: "clothing", emoji: "👚" },
  { name: "Outdoors", slug: "outdoors", emoji: "🏕️" },
  { name: "Food", slug: "food", emoji: "🍕" },
  { name: "Furniture", slug: "furniture", emoji: "🛋️" },
  { name: "Sports", slug: "sports", emoji: "⚽" },
  { name: "Pets", slug: "pets", emoji: "🐶" },
  { name: "Books", slug: "books", emoji: "📚" },
  { name: "Music", slug: "music", emoji: "🎧" },
  { name: "Media", slug: "media", emoji: "📺" },
  { name: "Gaming", slug: "gaming", emoji: "🎮" },
  // { name: "Travel", slug: "travel", emoji: "🚀" },
  // { name: "Health", slug: "health", emoji: "🏥" },
  // { name: "Real Estate", slug: "real-estate", emoji: "🏘️" },
];
