export const CompanyData = [
  {
    slug: "honda",
    name: "Honda",
    description: "Cars and more.",
    tags: [
      "automotive",
      "automotive",
      "automotive",
      "automotive",
      "automotive",
    ],
    logoUrl: "",
    screenshot: "",
  },
  {
    slug: "kleintools",
    name: "Klein Tools",
    description: "Tools and stuff.",
    domain: "kleintools.com",
    url: "https://www.kleintools.com/content/american-manufacturing",
    tags: ["tools"],
    logo: "https://www.kleintools.com/sites/default/files/images/logos/kt-lineman-coin.png",
    screenshot: "https://api.pikwy.com/web/6573ac647aaf946ba46f048b.jpg",
    address: "500 Klein Tools Blvd, Mansfield, TX 76063",
    latitude: 32.5806,
    longitude: -97.1395,
  },
  {
    slug: "ford",
    name: "Ford",
    description:
      "Ford Motor Company is an American multinational automobile manufacturer headquartered in Dearborn, Michigan, United States. It was founded by Henry Ford and incorporated on June 16, 1903. The company sells automobiles and commercial vehicles under the Ford brand, and luxury cars under its Lincoln brand.",
    tags: ["automotive", "manufacturing"],
    logo: "",
    screenshot: "",
    // locations: [],
    domain: "ford.com",
    phone: "+18003923673",
    founder: "Henry Ford",
    founded: "1903-06-16T00:00:00.000Z",
  },
  {
    slug: "ge",
    name: "General Electric",
    description: "Multinational conglomerate.",
    tags: ["manufacturing", "technology"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "boeing",
    name: "Boeing",
    description: "Aerospace manufacturer.",
    tags: ["manufacturing", "aerospace"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "general-motors",
    name: "General Motors",
    description: "Automobile manufacturer.",
    tags: ["automotive", "manufacturing"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "caterpillar",
    name: "Caterpillar Inc.",
    description: "Multinational construction equipment manufacturer.",
    tags: ["manufacturing", "construction"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "john-deere",
    name: "John Deere",
    description: "Agricultural equipment manufacturer.",
    tags: ["manufacturing", "agriculture"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "honeywell",
    name: "Honeywell",
    description: "Multinational conglomerate.",
    tags: ["energy", "technology"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "goodyear",
    name: "Goodyear",
    description: "Tire manufacturer.",
    tags: ["tires", "automotive"],
    logo: "",
    screenshot: "",
  },
  {
    slug: "llbean",
    name: "LLBean",
    description: "Tire manufacturer.",
    tags: ["clothing", "outdoors"],
    logo: "",
    screenshot: "",
  },
];
